basePath: /
definitions:
  models.Student:
    properties:
      adress:
        type: string
      course:
        type: integer
      createdAt:
        type: string
      deletedAt:
        type: string
      department:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: integer
      surname:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:4000
info:
  contact:
    email: support@swagger.io
    name: API supporter
    url: http://www.swagger.io/support
  description: Description of specifications
  license:
    name: license(Mandatory)
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: API document title
  version: version(1.0)
paths:
  /student:
    get:
      consumes:
      - application/json
      description: get all students from the database.
      operationId: get-all-Students
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: struct
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Student'
      summary: Show student list.
      tags:
      - Students
    post:
      consumes:
      - application/json
      description: create a student and add to the database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Student'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Student'
      summary: Create a new student.
      tags:
      - Students
  /student/:id:
    delete:
      consumes:
      - application/json
      description: delete an existing student by ID.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: struct
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Student'
      summary: Delete a student.
      tags:
      - Students
    get:
      consumes:
      - application/json
      description: get one student by id from the database.
      operationId: get-Student-by-id
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: struct
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Student'
      summary: Show a  student from the list.
      tags:
      - Students
    put:
      consumes:
      - application/json
      description: update an existing student by ID.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: struct
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Student'
      summary: Update a student.
      tags:
      - Students
swagger: "2.0"
